### ISSUE TITLE
had to manually upgrade mongoose to avoid github.com/Automattic/mongoose/issues/2587

### ISSUE THREAD

**Issue by gpolyn** [heroku-examples/node-articles-nlp#11]
FYI - on node 0.10.33 and mongodb 3.0.1 I had to upgrade mongoose to 4.0.0 to avoid github.com/Automattic/mongoose/issues/2587

**Comment by perrygovier** [comment]
Ditto, updating packge.json to say `"mongoose": "^4.0.3",` worked fine for me

**Comment by gpolyn** [comment]
Yes, it does.
